[project]
authors = ["Julian Rüth <julian.rueth@fsfe.org>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "flatsurf"
platforms = ["linux-64", "osx-64"]
version = "0.5.2.post394"

[tasks]

[dependencies]
bidict = "*"
ipywidgets = "*"
jupyterlab = "*"
more-itertools = "*"
pyeantic = ">=2,<3"
pyexactreal = ">=4,<5"
pyflatsurf = ">=3.15.0,<4"
pyintervalxt = ">=3,<4"
sage = "10.3.*"
surface-dynamics = ">=0.6.0,<0.7"
veerer = ">=0.2.0,<0.3.0"

[pypi-dependencies]
jupyter-ui-poll = ">=0.2.1, <0.3"
flipper = "*"
ipyvue-flatsurf = ">=0.6.0, <0.7"
sage-flatsurf = { git = "https://github.com/flatsurf/sage-flatsurf.git", rev="f1cbb4abb3507e7fdf65e062677dd7dbf9a16bdc" }
