# This exnvironment.yml can be used to create a conda environment with
# sage-flatsurf and all its dependencies installed. It is used for our demo
# binders.
name: binder
channels:
  - flatsurf
  - conda-forge
dependencies:
  - sagelib
  - sympy
  - scipy
  - notebook
  - pyflatsurf>=3.6.4,<4
  - matplotlib-base
  - surface-dynamics>=0.4.7
  - jupytext
  - pip:
    - git+https://github.com/flatsurf/sage-flatsurf.git@991450e8f750cc3a583f248155787a6b087de6c0
    - flipper
