# This file lists the dependencies needed to build and test all of
# sage-flatsurf. Create a conda environment with these dependencies
# preinstalled with:
# conda env create -f environment.yml
name: sage-flatsurf-build
channels:
  - conda-forge
  - defaults
dependencies:
  - gap-defaults
  - ipywidgets
  - matplotlib-base
  - pip
  - pytest
  - pytest-xdist
  - sagelib>=8.8
  - scipy
  - surface-dynamics>=0.4.7
  - pyeantic>=1,<2  # optional: eantic
  - pyexactreal>=2,<3  # optional: exactreal
  - pyflatsurf>=3.10.1,<4  # optional: pyflatsurf
  - pip: [flipper]  # optional: flipper
