name: Publish to Anaconda
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: conda-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conda-build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: docker pull condaforge/linux-anvil-comp7
    - name: Build sage-flatsurf
      uses: flatsurf/actions/conda-forge-build@main
      with:
        recipe: recipe
    - uses: conda-incubator/setup-miniconda@v2
      with: {
        miniforge-variant: "Mambaforge",
        miniforge-version: "latest",
        # Default Python version for binder:
        # https://github.com/jupyterhub/repo2docker/blob/master/repo2docker/buildpacks/conda/environment.yml
        python-version: "3.7.12"
      }
    - name: Install package like binder would
      run: |
        wget -O repo2docker.yml https://github.com/jupyterhub/repo2docker/raw/main/repo2docker/buildpacks/conda/environment.yml
        mamba install -n test --quiet -y pytest pytest-xdist
        mamba env update -n test --quiet -f repo2docker.yml
        conda config --set 'custom_channels.conda-build' file://${{ github.workspace }}
        sed 's/  - sage-flatsurf=.*/  - conda-build::sage-flatsurf/' < binder/environment.yml > environment.binder.yml
        cat environment.binder.yml
        mamba env update -n test --quiet -f environment.binder.yml
        conda list
    - name: Initialize cppyy
      run: |
        # Show message about cppyy regenerating pre-compiled headers so it does not show during the tests
        python -c 'import cppyy' || true
    - name: Run SageMath doctests
      run: |
        export PYTHONPATH=test/disable-pytest:$PYTHONPATH
        sage -tp --force-lib --long --optional=sage,flipper,eantic,exactreal,pyflatsurf flatsurf doc
    - name: Run pytest
      run: pytest -n auto
    - uses: actions/upload-artifact@v2
      with:
        name: conda-packages
        path: conda-build/
    - uses: flatsurf/actions/anaconda-upload@main
      with:
        user: flatsurf
        token: ${{ secrets.BINSTAR_TOKEN }}
  conda-pack:
    runs-on: "${{ matrix.on }}"
    strategy:
      matrix:
        on: [ubuntu-22.04, macos-11]
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        if: ${{ matrix.on == 'ubuntu-22.04' }}
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest", python-version: "${{ matrix.python }}" }
      - name: Install sage-flatsurf stack
        shell: bash -l {0}
        run: |
          mamba env create -n flatsurf -f flatsurf.yml
          # Add mamba so users can install optional packages later.
          mamba install -n flatsurf -y mamba
      - name: Install conda-pack
        shell: bash -l {0}
        run: |
          mamba install -y conda-pack makeself
      - name: Install sage-flatsurf
        shell: bash -l {0}
        run: |
          conda activate flatsurf
          pip install --verbose --no-index .
      - name: Freeze environment
        shell: bash -l {0}
        run: |
          mamba env export -n flatsurf -f conda-pack.yml --override-channels -c conda-forge
      - name: Maximize build space
        shell: bash -l {0}
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
          sudo gem uninstall -aIx
          sudo rm -rf /usr/local/miniconda
          sudo rm -rf /usr/local/lib/node_modules
          mamba env remove -n flatsurf --yes
        if: ${{ matrix.on == 'macos-11' }}
      - name: Create installer
        shell: bash -l {0}
        run: |
          mamba create -n flatsurf mamba pip --yes
          conda activate flatsurf
          pip install --no-deps .
          conda deactivate
          conda pack -n flatsurf --n-threads 2
          mv conda-pack.yml pack/
          tar -zxf flatsurf.tar.gz -C pack
          find pack/lib -name '*.dylib' -type f -exec strip -S \{\} \; # macOS
          find pack/lib -name '*.so' -type f -exec strip --strip-unneeded \{\} \; # Linux
          mkdir tmp
          TMPDIR=$PWD/tmp/ makeself --complevel 6 --target ./flatsurf-0.5.2 pack/ flatsurf.install flatsurf ./unpack.sh

env:
  MAKEFLAGS: -j4
  SAGE_NUM_THREADS: 4
