name: Publish to Anaconda
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: conda-${{ github.ref }}
  cancel-in-progress: true

jobs:
  conda-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: docker pull condaforge/linux-anvil-comp7
    - name: Build sage-flatsurf
      uses: flatsurf/actions/conda-forge-build@main
      with:
        recipe: recipe
    - uses: conda-incubator/setup-miniconda@v2
      with: {
        miniforge-variant: "Mambaforge",
        miniforge-version: "latest",
        # Default Python version for binder:
        # https://github.com/jupyterhub/repo2docker/blob/master/repo2docker/buildpacks/conda/environment.yml
        python-version: "3.7.12"
      }
    - name: Install package like binder would
      shell: bash -l {0}
      run: |
        wget -O repo2docker.yml https://github.com/jupyterhub/repo2docker/raw/main/repo2docker/buildpacks/conda/environment.yml
        mamba install -n test --quiet -y pytest pytest-xdist
        mamba env update -n test --quiet -f repo2docker.yml
        conda config --set 'custom_channels.conda-build' file://${{ github.workspace }}
        sed 's/  - sage-flatsurf=.*/  - conda-build::sage-flatsurf/' < binder/environment.yml > environment.binder.yml
        mamba env update -n test --quiet -f environment.binder.yml
        conda list
    - name: Initialize cppyy
      shell: bash -l {0}
      run: |
        # Show message about cppyy regenerating pre-compiled headers so it does not show during the tests
        python -c 'import cppyy' || true
    - name: Run SageMath doctests
      shell: bash -l {0}
      run: |
        export PYTHONPATH=test/disable-pytest:$PYTHONPATH
        sage -tp --force-lib --long --optional=sage,flipper,eantic,exactreal,pyflatsurf flatsurf doc
    - name: Run pytest
      shell: bash -l {0}
      run: pytest -n auto
    - uses: actions/upload-artifact@v2
      with:
        name: conda-packages
        path: conda-build/
    - uses: flatsurf/actions/anaconda-upload@main
      with:
        user: flatsurf
        token: ${{ secrets.BINSTAR_TOKEN }}

env:
  MAKEFLAGS: -j2
  SAGE_NUM_THREADS: 2
