name: Build Installer
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: installer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unix:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }
    - name: Create installer
      run: ./installer/unix/build-installer.sh
    - name: Provide installer as a build artifact
      uses: actions/upload-artifact@v3
      with:
        name: unix-installer
        path: installer/unix/sage-flatsurf*.pixi.tar.gz

  # TODO: windows
  # TODO: test unix installer
